name: Release

on:
  push:
    tags:
      - 'v*'

<<<<<<< HEAD
=======
permissions:
  contents: write

>>>>>>> 03ff6d6 (:construction_worker: 添加 goreleaser)
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}